# Generated by Django 3.2.14 on 2023-11-29 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription_Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Period', models.PositiveIntegerField()),
                ('Category', models.CharField(choices=[('Month', 'Month'), ('Year', 'Year')], max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='Period_Of_Subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Members.subscription_period'),
        ),
    ]
